# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  barberdule_config = debug_win64

else ifeq ($(config),debug_linux)
  barberdule_config = debug_linux

else ifeq ($(config),release_win64)
  barberdule_config = release_win64

else ifeq ($(config),release_linux)
  barberdule_config = release_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := barberdule

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

barberdule:
ifneq (,$(barberdule_config))
	@echo "==== Building barberdule ($(barberdule_config)) ===="
	@${MAKE} --no-print-directory -C . -f barberdule.make config=$(barberdule_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f barberdule.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_linux"
	@echo "  release_win64"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   barberdule"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"